// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCz1ZImpm__EGJiiI3nXqoX0fagS7m31Cw',
    appId: '1:518414272878:web:089bcc706349214b15197f',
    messagingSenderId: '518414272878',
    projectId: 'tadadak-2b531',
    authDomain: 'tadadak-2b531.firebaseapp.com',
    storageBucket: 'tadadak-2b531.firebasestorage.app',
    measurementId: 'G-RNM5GHLNQ0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZc2T3vjp64E6JDUPrhzG9FOCX540tccU',
    appId: '1:518414272878:android:01685a1b93fdf82215197f',
    messagingSenderId: '518414272878',
    projectId: 'tadadak-2b531',
    storageBucket: 'tadadak-2b531.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDTeEO6vx-8VhnxpY6GI7nsFSIwtA-IBc',
    appId: '1:518414272878:ios:cc4efc2943791fb015197f',
    messagingSenderId: '518414272878',
    projectId: 'tadadak-2b531',
    storageBucket: 'tadadak-2b531.firebasestorage.app',
    iosBundleId: 'com.example.tadaktakApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDTeEO6vx-8VhnxpY6GI7nsFSIwtA-IBc',
    appId: '1:518414272878:ios:cc4efc2943791fb015197f',
    messagingSenderId: '518414272878',
    projectId: 'tadadak-2b531',
    storageBucket: 'tadadak-2b531.firebasestorage.app',
    iosBundleId: 'com.example.tadaktakApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCz1ZImpm__EGJiiI3nXqoX0fagS7m31Cw',
    appId: '1:518414272878:web:27a4522c81789a7115197f',
    messagingSenderId: '518414272878',
    projectId: 'tadadak-2b531',
    authDomain: 'tadadak-2b531.firebaseapp.com',
    storageBucket: 'tadadak-2b531.firebasestorage.app',
    measurementId: 'G-F1RJF93J90',
  );
}
